### PR TITLE
Added Hue shift brushes

### PR DESCRIPTION
**Pull request by ThePreviousOne**
these are variations on the standard Airbrush_linear_noisy (as you may have guessed from their names)

They both stay within the selected colours range and adjust according to pen pressure. The light one lowers the saturation helping to give the colour a lighter feel. And the Dark one lowers the value to do the opposite.

personally I like them for shading/lighting, but I imagine they could be useful elsewhere as well.

### CODE REVIEW

**Comment by ThePreviousOne** [comment]
Sorry about the multiple pushes, I added the wrong files.
nevermind im an idiot

**Comment by Deevad** [comment]
Hey, thank you for the brush. I'll test it.  Is it compatible with 3.x or designed in 4.x ? 
[This is](http://www.gregwrightillustration.com/) the type of texture it does? 
May be you can propose them for Krita 4.x ? an active discussion is happening here  https://phabricator.kde.org/T7424

**Comment by ThePreviousOne** [comment]
Actually yes it is. I figured out that I needed to bundle them I so I'll put that up now.
They are for 3.x

**Comment by ThePreviousOne** [comment]
oops new PR
https://github.com/Deevad/deevad-krita-brushpresets/pull/9

**Comment by Deevad** [comment]
Hey, meanwhile I took maintenance of the default brushes in Krita 4.x ; and my repo will probably disappear because I'll keep maintaining directly in Krita.

About your brushes; I tested the two of them:
2018-03-05_screenshot_125326_net

The bundle is well done, it's good for distributing it. I'll not insert it in my brushkit here because it's not the type of brush I'm using: the grain is a bit too digital and noisy for my taste ; and brushkit are matter of taste. 
For inclusion in 4.x; I aleady added Charcoal-pencil-large ; producing also a large texture stroke with fading around the middle of the spot ( and with a slightly more natural grain ). It will duplicate the effect, and with over 120 brushes, I'm looking all the way to reduce more than to expand. 

If you have other brushes to propose, let me know! I always have fun to test and review ; And if you develop a bundle with your own brush and style ; I advice you to edit the wiki here https://docs.krita.org/Resources and add a preview picture so it will help other users.

**Pull request closed without merging**
